version: '3.8'

services:
  fana-bot:
    build: .
    container_name: fana-md-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./session:/app/session
      - ./temp:/app/temp
      - ./media:/app/media
      - ./auth_info.json:/app/auth_info.json
    environment:
      - NODE_ENV=production
      - TZ=Africa/Nairobi
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
